nelmio_api_doc:
    documentation:
        info:
            title: CoTerazGramy??
            description: Aplikacja do przezentacji notatek dla zespołów
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc(.json)?$) # Accepts routes under /api except /api/doc
