version: '3'

services:
  php:
    build:
      context: docker/php
    user: "1000:1000"
    volumes:
      - ./:/var/www/app
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
    working_dir: /var/www/app

  nginx:
    image: nginx:1.20-alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/app
    ports:
      - "80:80"

  database:
    image: postgres:13-alpine
#    volumes:
#      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

volumes:
  db-data:
